# Aula 04 - Avaliação de Estratégias de Chunking com LangChain

## Teste 1 - Chunk fixo de 200 caracteres, sem overlap

In [1]:
from langchain_text_splitters import CharacterTextSplitter
from pathlib import Path

c:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
arquivo = Path("markdown/bioetica_e_ia.md")

texto = arquivo.read_text(encoding="utf-8")

print("Quantidade de caracteres:", len(texto))

Quantidade de caracteres: 44347


In [3]:
splitter = CharacterTextSplitter(
    separator="",
    chunk_size=200,
    chunk_overlap=0
)

In [4]:
chunks = splitter.split_text(texto)

print("Quantidade de chunks:", len(chunks))

Quantidade de chunks: 222


In [5]:
for i, chunk in enumerate(chunks[:5], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medic
Tamanho: 200
CHUNK 2
ina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de t
Tamanho: 200
CHUNK 3
riagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidad
Tamanho: 200
CHUNK 4
os especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à au
Tamanho: 200
CHUNK 5
tonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificia

In [6]:
tamanhos = [len(chunk) for chunk in chunks]

print("Número total de chunks:", len(chunks))
print("Tamanho médio:", sum(tamanhos) / len(tamanhos))
print("Tamanho mínimo:", min(tamanhos))
print("Tamanho máximo:", max(tamanhos))
print("Overlap:", 0)

Número total de chunks: 222
Tamanho médio: 199.4189189189189
Tamanho mínimo: 146
Tamanho máximo: 200
Overlap: 0


In [7]:
splitter_teste_2 = CharacterTextSplitter(
    separator="",
    chunk_size=500,
    chunk_overlap=0
)

chunks_teste_2 = splitter_teste_2.split_text(texto)

tamanhos_teste_2 = [len(chunk) for chunk in chunks_teste_2]

print("Número total de chunks:", len(chunks_teste_2))
print("Tamanho médio:", sum(tamanhos_teste_2) / len(tamanhos_teste_2))
print("Tamanho mínimo:", min(tamanhos_teste_2))
print("Tamanho máximo:", max(tamanhos_teste_2))
print("Overlap:", 0)

Número total de chunks: 89
Tamanho médio: 497.92134831460675
Tamanho mínimo: 347
Tamanho máximo: 500
Overlap: 0


In [8]:
for i, chunk in enumerate(chunks_teste_2[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoc
Tamanho: 500
CHUNK 2
es, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valo

### Observação do Teste 2

O chunking fixo de 500 caracteres reduziu a quantidade de chunks em relação
ao teste de 200 caracteres, porém ainda apresentou fragmentação de palavras,
sentenças e parágrafos.

Isso ocorre porque a divisão considera apenas a quantidade de caracteres,
sem levar em conta a estrutura semântica do texto.

In [9]:
tamanhos_teste_2 = [len(chunk) for chunk in chunks_teste_2]

print("Número total de chunks:", len(chunks_teste_2))
print("Tamanho médio:", sum(tamanhos_teste_2) / len(tamanhos_teste_2))
print("Tamanho mínimo:", min(tamanhos_teste_2))
print("Tamanho máximo:", max(tamanhos_teste_2))
print("Overlap:", 0)

Número total de chunks: 89
Tamanho médio: 497.92134831460675
Tamanho mínimo: 347
Tamanho máximo: 500
Overlap: 0


In [10]:
splitter_teste_3 = CharacterTextSplitter(
    separator="",
    chunk_size=1000,
    chunk_overlap=0
)

chunks_teste_3 = splitter_teste_3.split_text(texto)

tamanhos_teste_3 = [len(chunk) for chunk in chunks_teste_3]

print("Número total de chunks:", len(chunks_teste_3))
print("Tamanho médio:", sum(tamanhos_teste_3) / len(tamanhos_teste_3))
print("Tamanho mínimo:", min(tamanhos_teste_3))
print("Tamanho máximo:", max(tamanhos_teste_3))
print("Overlap:", 0)

Número total de chunks: 45
Tamanho médio: 985.1333333333333
Tamanho mínimo: 347
Tamanho máximo: 1000
Overlap: 0


In [11]:
for i, chunk in enumerate(chunks_teste_3[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este arti

### Observação do Teste 3

O aumento do tamanho para 1000 caracteres permitiu que cada chunk carregasse
mais contexto em comparação aos testes anteriores. Entretanto, a divisão fixa
por caracteres ainda provocou cortes no meio de palavras, frases e estruturas
do documento.

Isso mostra que apenas aumentar o `chunk_size` não garante preservação
semântica do conteúdo.

In [12]:
tamanhos_teste_3 = [len(chunk) for chunk in chunks_teste_3]

print("Número total de chunks:", len(chunks_teste_3))
print("Tamanho médio:", sum(tamanhos_teste_3) / len(tamanhos_teste_3))
print("Tamanho mínimo:", min(tamanhos_teste_3))
print("Tamanho máximo:", max(tamanhos_teste_3))
print("Overlap:", 0)

Número total de chunks: 45
Tamanho médio: 985.1333333333333
Tamanho mínimo: 347
Tamanho máximo: 1000
Overlap: 0


In [13]:
splitter_teste_4 = CharacterTextSplitter(
    separator="",
    chunk_size=2000,
    chunk_overlap=0
)

chunks_teste_4 = splitter_teste_4.split_text(texto)

tamanhos_teste_4 = [len(chunk) for chunk in chunks_teste_4]

print("Número total de chunks:", len(chunks_teste_4))
print("Tamanho médio:", sum(tamanhos_teste_4) / len(tamanhos_teste_4))
print("Tamanho mínimo:", min(tamanhos_teste_4))
print("Tamanho máximo:", max(tamanhos_teste_4))
print("Overlap:", 0)

Número total de chunks: 23
Tamanho médio: 1927.8695652173913
Tamanho mínimo: 347
Tamanho máximo: 2000
Overlap: 0


In [14]:
for i, chunk in enumerate(chunks_teste_4[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("Tamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este arti

### Observação do Teste 4

Com chunks de 2000 caracteres, cada trecho passou a concentrar uma quantidade
maior de contexto em comparação aos testes anteriores.

Entretanto, a estratégia de divisão fixa por caracteres continuou provocando
cortes no meio de palavras, frases e estruturas do documento. Portanto,
aumentar o tamanho do chunk melhora a quantidade de contexto disponível,
mas não resolve o problema da fragmentação semântica.

In [15]:
tamanhos_teste_4 = [len(chunk) for chunk in chunks_teste_4]

print("Número total de chunks:", len(chunks_teste_4))
print("Tamanho médio:", sum(tamanhos_teste_4) / len(tamanhos_teste_4))
print("Tamanho mínimo:", min(tamanhos_teste_4))
print("Tamanho máximo:", max(tamanhos_teste_4))
print("Overlap:", 0)

Número total de chunks: 23
Tamanho médio: 1927.8695652173913
Tamanho mínimo: 347
Tamanho máximo: 2000
Overlap: 0


In [16]:
splitter_teste_5 = CharacterTextSplitter(
    separator="",
    chunk_size=500,
    chunk_overlap=50
)

chunks_teste_5 = splitter_teste_5.split_text(texto)

tamanhos_teste_5 = [len(chunk) for chunk in chunks_teste_5]

print("Número total de chunks:", len(chunks_teste_5))
print("Tamanho médio:", sum(tamanhos_teste_5) / len(tamanhos_teste_5))
print("Tamanho mínimo:", min(tamanhos_teste_5))
print("Tamanho máximo:", max(tamanhos_teste_5))
print("Overlap:", 50)

Número total de chunks: 99
Tamanho médio: 497.1313131313131
Tamanho mínimo: 246
Tamanho máximo: 500
Overlap: 50


In [17]:
print("FINAL DO CHUNK 1:")
print(chunks_teste_5[0][-150:])

print("\n" + "=" * 60)

print("INÍCIO DO CHUNK 2:")
print(chunks_teste_5[1][:150])

FINAL DO CHUNK 1:
temas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoc

INÍCIO DO CHUNK 2:
m demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidad


### Observação do Teste 5

O uso de `chunk_overlap = 50` fez com que parte do final de um chunk fosse repetida
no início do chunk seguinte.

Essa sobreposição ajuda a preservar o contexto em regiões de fronteira entre
os chunks, reduzindo o risco de fragmentar completamente uma ideia entre dois
trechos distintos.

Em contrapartida, o overlap gera redundância de conteúdo e tende a aumentar
a quantidade de informação processada e armazenada.

In [18]:
splitter_teste_6 = CharacterTextSplitter(
    separator="",
    chunk_size=500,
    chunk_overlap=200
)

chunks_teste_6 = splitter_teste_6.split_text(texto)

tamanhos_teste_6 = [len(chunk) for chunk in chunks_teste_6]

print("Número total de chunks:", len(chunks_teste_6))
print("Tamanho médio:", sum(tamanhos_teste_6) / len(tamanhos_teste_6))
print("Tamanho mínimo:", min(tamanhos_teste_6))
print("Tamanho máximo:", max(tamanhos_teste_6))
print("Overlap:", 200)

Número total de chunks: 148
Tamanho médio: 497.9054054054054
Tamanho mínimo: 246
Tamanho máximo: 500
Overlap: 200


In [19]:
print("FINAL DO CHUNK 1:")
print(chunks_teste_6[0][-250:])

print("\n" + "=" * 60)

print("INÍCIO DO CHUNK 2:")
print(chunks_teste_6[1][:250])

FINAL DO CHUNK 1:
 Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoc

INÍCIO DO CHUNK 2:
ransformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recurso


## Teste 7 - Chunking por Parágrafos

Nesta estratégia, o documento é dividido utilizando as quebras de parágrafo
como separadores, buscando preservar unidades textuais completas e reduzir
cortes arbitrários no conteúdo.

In [20]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter_teste_7 = RecursiveCharacterTextSplitter(
    separators=["\n\n"],
    chunk_size=1000,
    chunk_overlap=0,
    length_function=len
)

chunks_teste_7 = splitter_teste_7.split_text(texto)

print("Número total de chunks:", len(chunks_teste_7))

Número total de chunks: 57


In [21]:
for i, chunk in enumerate(chunks_teste_7[:5], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("\nTamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

Tamanho: 257
CHUNK 2


O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e val

In [22]:
tamanhos_teste_7 = [len(chunk) for chunk in chunks_teste_7]

print("Número total de chunks:", len(chunks_teste_7))
print("Tamanho médio:", round(sum(tamanhos_teste_7) / len(tamanhos_teste_7), 2))
print("Tamanho mínimo:", min(tamanhos_teste_7))
print("Tamanho máximo:", max(tamanhos_teste_7))

Número total de chunks: 57
Tamanho médio: 776.33
Tamanho mínimo: 195
Tamanho máximo: 1360


### Observação do Teste 7

A estratégia baseada em parágrafos preservou melhor as unidades textuais naturais
do documento e evitou cortes arbitrários no meio das palavras.

Entretanto, alguns parágrafos possuem mais de 1000 caracteres, fazendo com que
determinados chunks ultrapassem o valor definido em `chunk_size`.

Esse comportamento ocorre porque, neste experimento, foi utilizado apenas
`\n\n` como separador, priorizando a preservação integral dos parágrafos.

O resultado evidencia um dos trade-offs do chunking estrutural: maior coerência
semântica pode resultar em chunks de tamanhos menos uniformes.

In [23]:
tamanhos_teste_7 = [len(chunk) for chunk in chunks_teste_7]

print("Número total de chunks:", len(chunks_teste_7))
print("Tamanho médio:", round(sum(tamanhos_teste_7) / len(tamanhos_teste_7), 2))
print("Tamanho mínimo:", min(tamanhos_teste_7))
print("Tamanho máximo:", max(tamanhos_teste_7))

Número total de chunks: 57
Tamanho médio: 776.33
Tamanho mínimo: 195
Tamanho máximo: 1360


## Teste 8 - Sentenças agrupadas em 3

Nesta estratégia, o documento é dividido em sentenças e, em seguida,
três sentenças consecutivas são agrupadas em cada chunk.

O objetivo é avaliar se a utilização de sentenças completas preserva
melhor o contexto do que a divisão puramente baseada em caracteres.

In [24]:
!pip install nltk


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
import nltk

nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ResTIC16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [26]:
from nltk.tokenize import sent_tokenize

sentencas = sent_tokenize(
    texto,
    language="portuguese"
)

print("Número total de sentenças:", len(sentencas))

Número total de sentenças: 256


In [27]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ResTIC16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ResTIC16\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [28]:
from nltk.tokenize import sent_tokenize

sentencas = sent_tokenize(
    texto,
    language="portuguese"
)

print("Número total de sentenças:", len(sentencas))

Número total de sentenças: 256


In [29]:
chunks_teste_8 = []

for i in range(0, len(sentencas), 3):
    grupo = sentencas[i:i+3]

    chunk = " ".join(grupo)

    chunks_teste_8.append(chunk)

print("Número total de chunks:", len(chunks_teste_8))

Número total de chunks: 86


In [30]:
tamanhos_teste_8 = [len(chunk) for chunk in chunks_teste_8]

print("Número total de chunks:", len(chunks_teste_8))
print("Tamanho médio:", round(sum(tamanhos_teste_8) / len(tamanhos_teste_8), 2))
print("Tamanho mínimo:", min(tamanhos_teste_8))
print("Tamanho máximo:", max(tamanhos_teste_8))

Número total de chunks: 86
Tamanho médio: 513.5
Tamanho mínimo: 56
Tamanho máximo: 1088


In [31]:
for i, chunk in enumerate(chunks_teste_8[:3], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("\nTamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal. ## Resumo

O avanço da inteligência artificial tem transformado profundamente a prática médica.

Tamanho: 342
CHUNK 2
De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valor

### Observação do Teste 8

O agrupamento de três sentenças por chunk produziu trechos com tamanhos
variáveis, pois o comprimento das sentenças não é uniforme.

Em comparação com o chunking fixo por caracteres, essa estratégia preservou
melhor unidades completas de sentido, reduzindo cortes no meio de palavras e
frases.

Como desvantagem, os chunks ficaram menos uniformes em tamanho, o que pode
impactar custo e consistência no processamento posterior dos embeddings.

In [32]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter_teste_9 = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100,
    separators=[
        "\n\n",
        "\n",
        " ",
        ""
    ],
    length_function=len
)

chunks_teste_9 = splitter_teste_9.split_text(texto)

print("Número total de chunks:", len(chunks_teste_9))

Número total de chunks: 65


In [33]:
for i, chunk in enumerate(chunks_teste_9[:5], start=1):
    print("=" * 60)
    print(f"CHUNK {i}")
    print(chunk)
    print("\nTamanho:", len(chunk))

CHUNK 1
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

## Resumo

Tamanho: 257
CHUNK 2
O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Juramento de Hipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valor

In [34]:
tamanhos_teste_9 = [len(chunk) for chunk in chunks_teste_9]

print("Número total de chunks:", len(chunks_teste_9))
print("Tamanho médio:", round(sum(tamanhos_teste_9) / len(tamanhos_teste_9), 2))
print("Tamanho mínimo:", min(tamanhos_teste_9))
print("Tamanho máximo:", max(tamanhos_teste_9))
print("Overlap configurado:", 100)

Número total de chunks: 65
Tamanho médio: 695.02
Tamanho mínimo: 102
Tamanho máximo: 999
Overlap configurado: 100


## Teste 10 - Chunking por Estrutura Markdown

Nesta estratégia, o documento é dividido com base nos headings Markdown,
buscando preservar a organização semântica das seções e subseções.

Também são mantidos, sempre que possível, metadados relacionados ao heading
e à seção de origem de cada chunk.

In [35]:
from langchain_text_splitters import MarkdownHeaderTextSplitter

In [36]:
headers_to_split_on = [
    ("#", "titulo_nivel_1"),
    ("##", "titulo_nivel_2"),
    ("###", "titulo_nivel_3"),
]

In [37]:
splitter_teste_10 = MarkdownHeaderTextSplitter(
    headers_to_split_on=headers_to_split_on
)

In [38]:
chunks_teste_10 = splitter_teste_10.split_text(texto)

print("Número total de chunks:", len(chunks_teste_10))

Número total de chunks: 19


In [39]:
for i, chunk in enumerate(chunks_teste_10[:5], start=1):
    print("=" * 70)
    print(f"CHUNK {i}")
    
    print("\nMETADADOS:")
    print(chunk.metadata)
    
    print("\nCONTEÚDO:")
    print(chunk.page_content)
    
    print("\nTamanho:", len(chunk.page_content))

CHUNK 1

METADADOS:
{}

CONTEÚDO:
273  
<!-- image -->

Tamanho: 20
CHUNK 2

METADADOS:
{'titulo_nivel_2': 'Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial'}

CONTEÚDO:
Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1  
1. Faculdade de Medicina da Universidade do Porto, Porto, Portugal.

Tamanho: 132
CHUNK 3

METADADOS:
{'titulo_nivel_2': 'Resumo'}

CONTEÚDO:
O avanço da inteligência artificial tem transformado profundamente a prática médica. De sistemas de apoio à decisão clínica a algoritmos de triagem e diagnóstico, a inteligência artificial tem demons -trado potencial para diagnósticos precoces, terapias personalizadas, otimização de recursos, redução de erros e ampliação do acesso a cuidados especializados. Contudo, essa revolução tecnológica impõe desafios éticos significativos aos princípios clássicos da bioética, como beneficência, não maleficência, confidencialidade e respeito à autonomia do doente, consagrados desde o Ju

In [40]:
tamanhos_teste_10 = [
    len(chunk.page_content)
    for chunk in chunks_teste_10
]

print("Número total de chunks:", len(chunks_teste_10))
print(
    "Tamanho médio:",
    round(
        sum(tamanhos_teste_10) / len(tamanhos_teste_10),
        2
    )
)
print("Tamanho mínimo:", min(tamanhos_teste_10))
print("Tamanho máximo:", max(tamanhos_teste_10))

Número total de chunks: 19
Tamanho médio: 2283.53
Tamanho mínimo: 20
Tamanho máximo: 6946


### Observação do Teste 10

O chunking baseado na estrutura Markdown conseguiu preservar informações
estruturais do documento por meio dos headings e de seus respectivos metadados.

Diferentemente das estratégias baseadas em tamanho fixo, os chunks apresentaram
grande variação de tamanho, pois a divisão foi determinada pela estrutura das
seções do documento.

Essa estratégia apresenta como vantagem a preservação do contexto estrutural e
dos metadados das seções. Entretanto, se uma seção possuir grande quantidade de
conteúdo, o chunk resultante também pode se tornar muito extenso.

Para aplicações de RAG, uma possível estratégia seria combinar a divisão por
headings com uma segunda divisão dos conteúdos muito extensos.

In [41]:
import pandas as pd

resultados_testes = [
    {
        "Teste": 1,
        "Estratégia": "Fixo",
        "Chunk Size": 200,
        "Overlap": 0,
        "Nº Chunks": len(chunks),
        "Média": round(sum(tamanhos) / len(tamanhos), 2),
        "Mínimo": min(tamanhos),
        "Máximo": max(tamanhos)
    },
    {
        "Teste": 2,
        "Estratégia": "Fixo",
        "Chunk Size": 500,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_2),
        "Média": round(sum(tamanhos_teste_2) / len(tamanhos_teste_2), 2),
        "Mínimo": min(tamanhos_teste_2),
        "Máximo": max(tamanhos_teste_2)
    },
    {
        "Teste": 3,
        "Estratégia": "Fixo",
        "Chunk Size": 1000,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_3),
        "Média": round(sum(tamanhos_teste_3) / len(tamanhos_teste_3), 2),
        "Mínimo": min(tamanhos_teste_3),
        "Máximo": max(tamanhos_teste_3)
    },
    {
        "Teste": 4,
        "Estratégia": "Fixo",
        "Chunk Size": 2000,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_4),
        "Média": round(sum(tamanhos_teste_4) / len(tamanhos_teste_4), 2),
        "Mínimo": min(tamanhos_teste_4),
        "Máximo": max(tamanhos_teste_4)
    },
    {
        "Teste": 5,
        "Estratégia": "Fixo + Overlap",
        "Chunk Size": 500,
        "Overlap": 50,
        "Nº Chunks": len(chunks_teste_5),
        "Média": round(sum(tamanhos_teste_5) / len(tamanhos_teste_5), 2),
        "Mínimo": min(tamanhos_teste_5),
        "Máximo": max(tamanhos_teste_5)
    },
    {
        "Teste": 6,
        "Estratégia": "Fixo + Overlap",
        "Chunk Size": 500,
        "Overlap": 200,
        "Nº Chunks": len(chunks_teste_6),
        "Média": round(sum(tamanhos_teste_6) / len(tamanhos_teste_6), 2),
        "Mínimo": min(tamanhos_teste_6),
        "Máximo": max(tamanhos_teste_6)
    },
    {
        "Teste": 7,
        "Estratégia": "Parágrafos",
        "Chunk Size": 1000,
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_7),
        "Média": round(sum(tamanhos_teste_7) / len(tamanhos_teste_7), 2),
        "Mínimo": min(tamanhos_teste_7),
        "Máximo": max(tamanhos_teste_7)
    },
    {
        "Teste": 8,
        "Estratégia": "3 Sentenças",
        "Chunk Size": "-",
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_8),
        "Média": round(sum(tamanhos_teste_8) / len(tamanhos_teste_8), 2),
        "Mínimo": min(tamanhos_teste_8),
        "Máximo": max(tamanhos_teste_8)
    },
    {
        "Teste": 9,
        "Estratégia": "Recursive",
        "Chunk Size": 1000,
        "Overlap": 100,
        "Nº Chunks": len(chunks_teste_9),
        "Média": round(sum(tamanhos_teste_9) / len(tamanhos_teste_9), 2),
        "Mínimo": min(tamanhos_teste_9),
        "Máximo": max(tamanhos_teste_9)
    },
    {
        "Teste": 10,
        "Estratégia": "Markdown",
        "Chunk Size": "-",
        "Overlap": 0,
        "Nº Chunks": len(chunks_teste_10),
        "Média": round(sum(tamanhos_teste_10) / len(tamanhos_teste_10), 2),
        "Mínimo": min(tamanhos_teste_10),
        "Máximo": max(tamanhos_teste_10)
    }
]

df_resultados = pd.DataFrame(resultados_testes)

df_resultados

,Teste,Estratégia,Chunk Size,Overlap,Nº Chunks,Média,Mínimo,Máximo
0,1,Fixo,200,0,222,199.42,146,200
1,2,Fixo,500,0,89,497.92,347,500
2,3,Fixo,1000,0,45,985.13,347,1000
3,4,Fixo,2000,0,23,1927.87,347,2000
4,5,Fixo + Overlap,500,50,99,497.13,246,500
5,6,Fixo + Overlap,500,200,148,497.91,246,500
6,7,Parágrafos,1000,0,57,776.33,195,1360
7,8,3 Sentenças,-,0,86,513.50,56,1088
8,9,Recursive,1000,100,65,695.02,102,999
9,10,Markdown,-,0,19,2283.53,20,6946


## Comparação preliminar das estratégias

Os experimentos demonstraram que o tamanho do chunk influencia diretamente
a quantidade de fragmentos gerados. Entre os testes de tamanho fixo sem
overlap, o uso de 200 caracteres produziu 222 chunks, enquanto 2000
caracteres resultaram em apenas 23 chunks.

A introdução de overlap aumentou a quantidade de chunks. Para chunks de
500 caracteres, foram obtidos 89 chunks sem overlap, 99 com overlap de
50 caracteres e 148 com overlap de 200 caracteres. Esse resultado evidencia
o aumento da redundância causado pela sobreposição.

As estratégias estruturais apresentaram comportamentos diferentes. O
chunking por parágrafos gerou 57 chunks e preservou melhor unidades textuais,
enquanto o agrupamento de três sentenças produziu 86 chunks com tamanhos
variáveis.

O RecursiveCharacterTextSplitter apresentou 65 chunks, buscando equilibrar
o limite de tamanho com a preservação da estrutura textual.

Por fim, o MarkdownHeaderTextSplitter gerou apenas 19 chunks, apresentando
a maior média de tamanho entre as estratégias. Apesar de preservar headings
e metadados estruturais, algumas seções resultaram em chunks muito extensos.

In [42]:
experimentos = {
    1: {
        "strategy": "fixed",
        "chunk_size": 200,
        "chunk_overlap": 0,
        "chunks": chunks
    },

    2: {
        "strategy": "fixed",
        "chunk_size": 500,
        "chunk_overlap": 0,
        "chunks": chunks_teste_2
    },

    3: {
        "strategy": "fixed",
        "chunk_size": 1000,
        "chunk_overlap": 0,
        "chunks": chunks_teste_3
    },

    4: {
        "strategy": "fixed",
        "chunk_size": 2000,
        "chunk_overlap": 0,
        "chunks": chunks_teste_4
    },

    5: {
        "strategy": "fixed_with_overlap",
        "chunk_size": 500,
        "chunk_overlap": 50,
        "chunks": chunks_teste_5
    },

    6: {
        "strategy": "fixed_with_overlap",
        "chunk_size": 500,
        "chunk_overlap": 200,
        "chunks": chunks_teste_6
    },

    7: {
        "strategy": "paragraph",
        "chunk_size": 1000,
        "chunk_overlap": 0,
        "chunks": chunks_teste_7
    },

    8: {
        "strategy": "sentence",
        "chunk_size": None,
        "chunk_overlap": 0,
        "chunks": chunks_teste_8
    },

    9: {
        "strategy": "recursive",
        "chunk_size": 1000,
        "chunk_overlap": 100,
        "chunks": chunks_teste_9
    },

    10: {
        "strategy": "markdown",
        "chunk_size": None,
        "chunk_overlap": 0,
        "chunks": chunks_teste_10
    }
}

In [43]:
for teste_id, config in experimentos.items():
    print(
        f"Teste {teste_id}: "
        f"{config['strategy']} - "
        f"{len(config['chunks'])} chunks"
    )

Teste 1: fixed - 222 chunks
Teste 2: fixed - 89 chunks
Teste 3: fixed - 45 chunks
Teste 4: fixed - 23 chunks
Teste 5: fixed_with_overlap - 99 chunks
Teste 6: fixed_with_overlap - 148 chunks
Teste 7: paragraph - 57 chunks
Teste 8: sentence - 86 chunks
Teste 9: recursive - 65 chunks
Teste 10: markdown - 19 chunks


## Geração dos Embeddings

Nesta etapa, será utilizado o mesmo modelo de embeddings para todos os
experimentos, garantindo uma comparação consistente entre as diferentes
estratégias de chunking.

Inicialmente, a geração será testada em um único chunk antes do
processamento completo dos experimentos.

In [44]:
def get_embedding(texto):
    response = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=texto,
        encoding_format="float"
    )

    return response.data[0].embedding

In [51]:
chunk_teste = experimentos[1]["chunks"][0]

print(chunk_teste)
print("\nTamanho:", len(chunk_teste))

273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medic

Tamanho: 200


In [52]:
embedding_teste = get_embedding(chunk_teste)

print("Dimensão do embedding:", len(embedding_teste))
print("Primeiros 10 valores:")
print(embedding_teste[:10])

Dimensão do embedding: 2048
Primeiros 10 valores:
[-0.026153564453125, -0.0074920654296875, 0.01483154296875, 0.0230712890625, 0.0091094970703125, -0.02410888671875, -0.01184844970703125, 0.0236968994140625, -0.04168701171875, 0.004970550537109375]


In [53]:
from dotenv import load_dotenv
import os
from openai import OpenAI

In [54]:
load_dotenv("../.env")

api_key = os.getenv("OPENROUTER_API_KEY")

print("Chave encontrada?", api_key is not None)

Chave encontrada? True


In [55]:
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
)

In [56]:
import os
from dotenv import load_dotenv
from openai import OpenAI

# Carrega o arquivo .env que está na raiz AULA_01
load_dotenv("../.env")

api_key = os.getenv("OPENROUTER_API_KEY")

print("Chave encontrada?", api_key is not None)

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key
)

# Mesmo modelo utilizado na Aula 03
MODELO_EMBEDDING = "nvidia/llama-nemotron-embed-vl-1b-v2:free"

Chave encontrada? True


In [57]:
def get_embedding(texto):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=texto,
        encoding_format="float"
    )

    return resposta.data[0].embedding

In [50]:
chunk_teste = experimentos[1]["chunks"][0]

print("Texto que será enviado:")
print(chunk_teste)

embedding_teste = get_embedding(chunk_teste)

print("\nDimensão do embedding:", len(embedding_teste))
print("Primeiros 10 valores:")
print(embedding_teste[:10])

Texto que será enviado:
273

<!-- image -->

## Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial

Juracy Barbosa dos Santos 1 , Guilhermina Rego 1 , Rui Nunes 1

1. Faculdade de Medic

Dimensão do embedding: 2048
Primeiros 10 valores:
[-0.026153564453125, -0.0074920654296875, 0.01483154296875, 0.0230712890625, 0.0091094970703125, -0.02410888671875, -0.01184844970703125, 0.0236968994140625, -0.04168701171875, 0.004970550537109375]


In [58]:
import json
import time
from pathlib import Path

In [59]:
def obter_texto_chunk(chunk):
    if hasattr(chunk, "page_content"):
        return chunk.page_content
    return str(chunk)


def obter_metadata_chunk(chunk):
    if hasattr(chunk, "metadata"):
        return chunk.metadata
    return {}

In [60]:
resultados_embeddings = []

document_id = "doc01"
document_name = "bioetica_e_ia.md"

for teste_id, config in experimentos.items():

    print("=" * 60)
    print(f"PROCESSANDO TESTE {teste_id}")
    print(f"Estratégia: {config['strategy']}")
    print(f"Quantidade de chunks: {len(config['chunks'])}")

    for indice, chunk in enumerate(config["chunks"], start=1):

        texto_chunk = obter_texto_chunk(chunk)
        metadata = obter_metadata_chunk(chunk)

        try:
            embedding = get_embedding(texto_chunk)

            resultado = {
                "chunk_id": f"{document_id}_test{teste_id:02d}_chunk{indice:03d}",
                "document_id": document_id,
                "document_name": document_name,
                "test_id": teste_id,
                "strategy": config["strategy"],
                "chunk_size": config["chunk_size"],
                "chunk_overlap": config["chunk_overlap"],
                "text": texto_chunk,
                "embedding": embedding,
                "metadata": metadata
            }

            resultados_embeddings.append(resultado)

            print(
                f"Teste {teste_id} | "
                f"Chunk {indice}/{len(config['chunks'])} | "
                f"Embedding: {len(embedding)} dimensões"
            )

            # Pequena pausa para evitar muitas chamadas seguidas
            time.sleep(0.2)

        except Exception as erro:
            print(
                f"ERRO no Teste {teste_id}, "
                f"Chunk {indice}: {erro}"
            )

print("\nPROCESSAMENTO FINALIZADO")
print("Total de registros:", len(resultados_embeddings))

PROCESSANDO TESTE 1
Estratégia: fixed
Quantidade de chunks: 222
Teste 1 | Chunk 1/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 2/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 3/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 4/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 5/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 6/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 7/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 8/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 9/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 10/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 11/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 12/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 13/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 14/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 15/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 16/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 17/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 18/222 | Embedding: 2048 dimensões
Teste 1 | Chunk 19/222 | Em

In [61]:
pasta_resultados = Path("results")
pasta_resultados.mkdir(exist_ok=True)

arquivo_saida = pasta_resultados / "bioetica_e_ia_chunking_embeddings.json"

with open(arquivo_saida, "w", encoding="utf-8") as arquivo:
    json.dump(
        resultados_embeddings,
        arquivo,
        ensure_ascii=False,
        indent=2
    )

print("JSON salvo em:")
print(arquivo_saida)

JSON salvo em:
results\bioetica_e_ia_chunking_embeddings.json


In [62]:
summary = {
    "document": "bioetica_e_ia.md",
    "embedding_model": MODELO_EMBEDDING,
    "embedding_dimension": len(embedding_teste),
    "experiments": []
}

for teste_id, config in experimentos.items():

    chunks_config = config["chunks"]

    if teste_id == 10:
        tamanhos_config = [
            len(chunk.page_content)
            for chunk in chunks_config
        ]
    else:
        tamanhos_config = [
            len(str(chunk))
            for chunk in chunks_config
        ]

    summary["experiments"].append({
        "test_id": teste_id,
        "strategy": config["strategy"],
        "chunk_size": config["chunk_size"],
        "chunk_overlap": config["chunk_overlap"],
        "num_chunks": len(chunks_config),
        "avg_chunk_size": round(
            sum(tamanhos_config) / len(tamanhos_config),
            2
        ),
        "min_chunk_size": min(tamanhos_config),
        "max_chunk_size": max(tamanhos_config),
        "embedding_dimension": len(embedding_teste)
    })

In [63]:
arquivo_summary = Path("results") / "summary.json"

with open(arquivo_summary, "w", encoding="utf-8") as arquivo:
    json.dump(
        summary,
        arquivo,
        ensure_ascii=False,
        indent=2
    )

print("Summary criado:")
print(arquivo_summary)

Summary criado:
results\summary.json


# Análise dos Experimentos

## 1. Qual estratégia gerou mais chunks?

Entre os experimentos realizados, a estratégia com maior número de chunks foi o
Teste 1, com chunk_size de 200 caracteres e sem overlap.

Esse comportamento era esperado, pois quanto menor o tamanho máximo permitido
para cada chunk, maior é a quantidade de fragmentos necessários para representar
o documento completo.

## 2. Qual estratégia gerou menos chunks?

A estratégia que gerou menos chunks foi o MarkdownHeaderTextSplitter.

Essa estratégia utiliza a estrutura de headings do documento para definir as
divisões, produzindo menos chunks, porém com tamanhos significativamente maiores
e mais variáveis.

## 3. Como o tamanho dos chunks variou?

As estratégias baseadas em tamanho fixo produziram chunks mais uniformes.

Nos testes com 200, 500, 1000 e 2000 caracteres, o tamanho dos chunks se manteve
próximo ao limite configurado.

Já as estratégias baseadas em parágrafos, sentenças e headings apresentaram maior
variação, pois priorizam unidades estruturais ou semânticas do texto em vez de
limites rígidos de tamanho.

## 4. Qual estratégia preservou melhor a estrutura dos documentos?

O MarkdownHeaderTextSplitter apresentou a melhor preservação da estrutura
documental, pois manteve informações associadas aos headings e seções.

O chunking por parágrafos também preservou melhor a estrutura textual do que os
métodos puramente baseados em caracteres.

## 5. Como tabelas foram tratadas?

As tabelas já haviam sido convertidas para a representação Markdown durante a
etapa PDF → Markdown.

Nos chunkings baseados em caracteres, existe risco de fragmentação das linhas e
da estrutura da tabela.

Estratégias estruturais, especialmente Markdown e Recursive, tendem a apresentar
maior possibilidade de preservação, dependendo da posição e do tamanho da tabela.

## 6. Como imagens foram tratadas?

Durante a conversão para Markdown, algumas imagens foram representadas por
marcadores como:

`<!-- image -->`

Isso indica que a imagem em si não foi incorporada como conteúdo visual no
Markdown utilizado pelos experimentos.

Assim, o embedding textual não representa diretamente o conteúdo visual da
imagem.

## 7. Quais informações foram perdidas durante a conversão PDF → Markdown?

Foi possível observar perda parcial da estrutura visual original do PDF.

Entre os elementos afetados estão layout de páginas, posicionamento de imagens,
colunas, espaçamento e parte da formatação visual.

Também foram observadas palavras fragmentadas por hifenização proveniente do PDF.

## 8. O chunking por caracteres fragmentou conceitos ou estruturas importantes?

Sim.

Os testes de chunking fixo apresentaram cortes no meio de palavras, frases e
parágrafos.

Isso demonstra que a divisão baseada exclusivamente em número de caracteres pode
prejudicar a preservação do contexto semântico.

## 9. O chunking por parágrafo produziu chunks muito grandes?

Em alguns casos, sim.

Como determinados parágrafos possuíam mais caracteres do que o tamanho definido,
alguns chunks ultrapassaram o valor configurado.

Esse resultado mostra o equilíbrio necessário entre preservação semântica e
controle do tamanho dos chunks.

## 10. O chunking por sentença conseguiu preservar melhor o contexto?

O agrupamento de três sentenças reduziu os cortes arbitrários encontrados nas
estratégias baseadas em caracteres.

Essa abordagem preservou unidades completas de sentido, embora tenha produzido
chunks de tamanhos variados.

## 11. O Recursive Splitter apresentou vantagens?

Sim.

O RecursiveCharacterTextSplitter apresentou um equilíbrio entre controle de
tamanho e preservação da estrutura textual.

A estratégia tenta inicialmente separar por parágrafos, depois por linhas,
espaços e, por último, caracteres.

Isso reduz a fragmentação arbitrária quando comparado ao chunking fixo.

## 12. O Markdown Splitter conseguiu preservar a estrutura semântica?

Sim.

O MarkdownHeaderTextSplitter conseguiu associar conteúdo aos headings e preservar
metadados relacionados às seções.

Essa característica pode ser especialmente útil em sistemas de RAG, pois permite
recuperar não apenas o texto, mas também informações sobre a seção de origem.

## 13. Qual estratégia parece mais adequada para um sistema de RAG?

Entre as estratégias avaliadas, o RecursiveCharacterTextSplitter apresenta uma
boa relação entre tamanho dos chunks e preservação do contexto.

O MarkdownHeaderTextSplitter também apresentou vantagens importantes na
preservação da estrutura semântica.

Uma abordagem híbrida, combinando headings Markdown com uma subdivisão recursiva
das seções muito grandes, pode ser uma alternativa adequada para RAG.

## 14. Quais estratégias devem ser descartadas?

Os chunkings fixos muito pequenos, especialmente o de 200 caracteres, tendem a
fragmentar excessivamente o conteúdo e gerar grande quantidade de embeddings.

O overlap muito alto também pode ser menos interessante devido à grande
redundância e ao aumento do custo de processamento e armazenamento.

## 15. Quais estratégias devem ser utilizadas nos próximos experimentos?

As estratégias mais interessantes para os próximos testes são:

- RecursiveCharacterTextSplitter;
- MarkdownHeaderTextSplitter;
- chunking por parágrafos;
- eventualmente chunk fixo intermediário com overlap leve, como 500 caracteres
  com overlap 50, para comparação.

Essas estratégias apresentam melhor equilíbrio entre preservação de contexto,
estrutura semântica, quantidade de chunks e custo de processamento.

## Conversão automática dos PDFs para Markdown

Nesta etapa, todos os arquivos PDF presentes na pasta `artigos`
serão convertidos automaticamente para Markdown utilizando o Docling.

Os arquivos resultantes serão armazenados na pasta `markdown`.

In [64]:
import os
import gc
from pathlib import Path

# Reduz consumo de memória no Windows
os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption


PASTA_ARTIGOS = Path("artigos")
PASTA_MARKDOWN = Path("markdown")

PASTA_MARKDOWN.mkdir(
    parents=True,
    exist_ok=True
)


# Configuração mais leve do Docling
pipeline_options = PdfPipelineOptions()

# Como os artigos científicos normalmente já possuem texto digital,
# não precisamos usar OCR.
pipeline_options.do_ocr = False

# Mantemos análise de tabelas.
pipeline_options.do_table_structure = True

# Reduz uso de memória
pipeline_options.layout_batch_size = 1
pipeline_options.ocr_batch_size = 1
pipeline_options.table_batch_size = 1


converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_options=pipeline_options
        )
    }
)


arquivos_pdf = sorted(
    PASTA_ARTIGOS.glob("*.pdf")
)

print(
    "Quantidade de PDFs encontrados:",
    len(arquivos_pdf)
)

Quantidade de PDFs encontrados: 12


In [2]:
import os
import gc

os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption

pipeline_options = PdfPipelineOptions()

# PDFs acadêmicos já possuem texto digital
pipeline_options.do_ocr = False

# Vamos deixar desligado agora para consumir menos memória
pipeline_options.do_table_structure = False

# Reduz o processamento simultâneo
pipeline_options.layout_batch_size = 1
pipeline_options.ocr_batch_size = 1
pipeline_options.table_batch_size = 1

converter = DocumentConverter(
    format_options={
        InputFormat.PDF: PdfFormatOption(
            pipeline_options=pipeline_options
        )
    }
)

print("✅ Conversor Docling criado!")

c:\Users\ResTIC16\Downloads\AULA_01\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


✅ Conversor Docling criado!


In [6]:
%pip install pypdf

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
from pypdf import PdfReader

print("✅ pypdf funcionando!")

✅ pypdf funcionando!


In [8]:
from pathlib import Path
from pypdf import PdfReader
import gc

arquivo_pdf = Path("artigos/gpt3_language_models.pdf")
arquivo_saida = Path("markdown/gpt3_language_models.md")

# Processar apenas 2 páginas por vez
TAMANHO_BLOCO = 2

reader = PdfReader(str(arquivo_pdf))
total_paginas = len(reader.pages)

print("Arquivo:", arquivo_pdf.name)
print("Total de páginas:", total_paginas)
print("=" * 60)

partes_markdown = []

for inicio in range(1, total_paginas + 1, TAMANHO_BLOCO):
    fim = min(inicio + TAMANHO_BLOCO - 1, total_paginas)

    print(
        f"⏳ Processando páginas {inicio}-{fim} de {total_paginas}...",
        flush=True
    )

    try:
        resultado = converter.convert(
            arquivo_pdf,
            page_range=(inicio, fim)
        )

        markdown_parcial = resultado.document.export_to_markdown()

        partes_markdown.append(markdown_parcial)

        print(
            f"✅ Páginas {inicio}-{fim} concluídas!",
            flush=True
        )

        del resultado
        del markdown_parcial
        gc.collect()

    except Exception as erro:
        print(
            f"❌ ERRO nas páginas {inicio}-{fim}: {erro}",
            flush=True
        )
        gc.collect()

markdown_completo = "\n\n".join(partes_markdown)

arquivo_saida.write_text(
    markdown_completo,
    encoding="utf-8"
)

print("\n" + "=" * 60)
print("✅ CONVERSÃO FINALIZADA")
print("Arquivo criado:", arquivo_saida)
print("Tamanho:", arquivo_saida.stat().st_size, "bytes")

Arquivo: gpt3_language_models.pdf
Total de páginas: 75
⏳ Processando páginas 1-2 de 75...


[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 1272.08it/s]


✅ Páginas 1-2 concluídas!
⏳ Processando páginas 3-4 de 75...
✅ Páginas 3-4 concluídas!
⏳ Processando páginas 5-6 de 75...
✅ Páginas 5-6 concluídas!
⏳ Processando páginas 7-8 de 75...
✅ Páginas 7-8 concluídas!
⏳ Processando páginas 9-10 de 75...
✅ Páginas 9-10 concluídas!
⏳ Processando páginas 11-12 de 75...
✅ Páginas 11-12 concluídas!
⏳ Processando páginas 13-14 de 75...
✅ Páginas 13-14 concluídas!
⏳ Processando páginas 15-16 de 75...
✅ Páginas 15-16 concluídas!
⏳ Processando páginas 17-18 de 75...
✅ Páginas 17-18 concluídas!
⏳ Processando páginas 19-20 de 75...
✅ Páginas 19-20 concluídas!
⏳ Processando páginas 21-22 de 75...
✅ Páginas 21-22 concluídas!
⏳ Processando páginas 23-24 de 75...
✅ Páginas 23-24 concluídas!
⏳ Processando páginas 25-26 de 75...
✅ Páginas 25-26 concluídas!
⏳ Processando páginas 27-28 de 75...
✅ Páginas 27-28 concluídas!
⏳ Processando páginas 29-30 de 75...
✅ Páginas 29-30 concluídas!
⏳ Processando páginas 31-32 de 75...
✅ Páginas 31-32 concluídas!
⏳ Processando

In [15]:
from pathlib import Path
from pypdf import PdfReader
import gc

# ============================================================
# ARQUIVO QUE SERÁ CONVERTIDO
# ============================================================

arquivo_pdf = Path("artigos/scaling_laws_llm.pdf")
arquivo_saida = Path("markdown/scaling_laws_llm.md")
# Quantidade de páginas processadas por vez
TAMANHO_BLOCO = 2


# ============================================================
# VERIFICAR QUANTIDADE DE PÁGINAS
# ============================================================

reader = PdfReader(str(arquivo_pdf))
total_paginas = len(reader.pages)

print("Arquivo:", arquivo_pdf.name)
print("Total de páginas:", total_paginas)
print("=" * 60)


# ============================================================
# CONVERSÃO EM BLOCOS
# ============================================================

partes_markdown = []

for inicio in range(1, total_paginas + 1, TAMANHO_BLOCO):

    fim = min(
        inicio + TAMANHO_BLOCO - 1,
        total_paginas
    )

    print(
        f"⏳ Processando páginas {inicio}-{fim} "
        f"de {total_paginas}...",
        flush=True
    )

    try:

        resultado = converter.convert(
            arquivo_pdf,
            page_range=(inicio, fim)
        )

        markdown_parcial = (
            resultado.document.export_to_markdown()
        )

        partes_markdown.append(
            markdown_parcial
        )

        print(
            f"✅ Páginas {inicio}-{fim} concluídas!",
            flush=True
        )

        # Libera memória
        del resultado
        del markdown_parcial
        gc.collect()

    except Exception as erro:

        print(
            f"❌ ERRO nas páginas "
            f"{inicio}-{fim}: {erro}",
            flush=True
        )

        gc.collect()


# ============================================================
# JUNTAR TODOS OS BLOCOS
# ============================================================

markdown_completo = "\n\n".join(
    partes_markdown
)


# ============================================================
# SALVAR O MARKDOWN
# ============================================================

arquivo_saida.write_text(
    markdown_completo,
    encoding="utf-8"
)


# ============================================================
# RESULTADO
# ============================================================

print("\n" + "=" * 60)
print("✅ CONVERSÃO FINALIZADA")
print("Arquivo criado:", arquivo_saida)
print(
    "Tamanho:",
    arquivo_saida.stat().st_size,
    "bytes"
)

Arquivo: scaling_laws_llm.pdf
Total de páginas: 30
⏳ Processando páginas 1-2 de 30...
✅ Páginas 1-2 concluídas!
⏳ Processando páginas 3-4 de 30...
✅ Páginas 3-4 concluídas!
⏳ Processando páginas 5-6 de 30...
✅ Páginas 5-6 concluídas!
⏳ Processando páginas 7-8 de 30...
✅ Páginas 7-8 concluídas!
⏳ Processando páginas 9-10 de 30...
✅ Páginas 9-10 concluídas!
⏳ Processando páginas 11-12 de 30...
✅ Páginas 11-12 concluídas!
⏳ Processando páginas 13-14 de 30...
✅ Páginas 13-14 concluídas!
⏳ Processando páginas 15-16 de 30...
✅ Páginas 15-16 concluídas!
⏳ Processando páginas 17-18 de 30...
✅ Páginas 17-18 concluídas!
⏳ Processando páginas 19-20 de 30...
✅ Páginas 19-20 concluídas!
⏳ Processando páginas 21-22 de 30...
✅ Páginas 21-22 concluídas!
⏳ Processando páginas 23-24 de 30...
✅ Páginas 23-24 concluídas!
⏳ Processando páginas 25-26 de 30...
✅ Páginas 25-26 concluídas!
⏳ Processando páginas 27-28 de 30...
✅ Páginas 27-28 concluídas!
⏳ Processando páginas 29-30 de 30...
✅ Páginas 29-30 conc

In [16]:
from pathlib import Path

PASTA_ARTIGOS = Path("artigos")
PASTA_MARKDOWN = Path("markdown")

pdfs = sorted(PASTA_ARTIGOS.glob("*.pdf"))
mds = sorted(PASTA_MARKDOWN.glob("*.md"))

print("=" * 70)
print("VERIFICAÇÃO PDF → MARKDOWN")
print("=" * 70)

quantidade_ok = 0
faltando = []

for pdf in pdfs:
    md_esperado = PASTA_MARKDOWN / f"{pdf.stem}.md"

    if md_esperado.exists():
        tamanho = md_esperado.stat().st_size

        print(
            f"✅ OK     {pdf.name} "
            f"→ {md_esperado.name} "
            f"({tamanho:,} bytes)"
        )

        quantidade_ok += 1

    else:
        print(
            f"❌ FALTA  {pdf.name}"
        )

        faltando.append(pdf.name)

print("\n" + "=" * 70)
print("RESUMO")
print("=" * 70)

print("Total de PDFs:", len(pdfs))
print("Com Markdown:", quantidade_ok)
print("Faltando:", len(faltando))

if len(faltando) == 0:
    print("\n🎉 Todos os PDFs possuem arquivo Markdown!")
else:
    print("\n⚠️ PDFs ainda sem Markdown:")

    for nome in faltando:
        print(" -", nome)

VERIFICAÇÃO PDF → MARKDOWN
✅ OK     attention_is_all_you_need.pdf → attention_is_all_you_need.md (11,580 bytes)
✅ OK     bert_pretraining.pdf → bert_pretraining.md (38,218 bytes)
✅ OK     bioetica_e_ia.pdf → bioetica_e_ia.md (46,033 bytes)
✅ OK     escrita_academica_ia.pdf → escrita_academica_ia.md (36,911 bytes)
✅ OK     gpt3_language_models.pdf → gpt3_language_models.md (288,939 bytes)
✅ OK     gpt4_technical_report.pdf → gpt4_technical_report.md (283,980 bytes)
✅ OK     instruct_gpt.pdf → instruct_gpt.md (205,631 bytes)
✅ OK     llama_foundation_models.pdf → llama_foundation_models.md (101,599 bytes)
✅ OK     lora_low_rank_adaptation.pdf → lora_low_rank_adaptation.md (97,723 bytes)
✅ OK     retrieval_augmented_generation.pdf → retrieval_augmented_generation.md (71,875 bytes)
✅ OK     scaling_laws_llm.pdf → scaling_laws_llm.md (96,800 bytes)
✅ OK     twitter_algoritmo.pdf → twitter_algoritmo.md (37,062 bytes)

RESUMO
Total de PDFs: 12
Com Markdown: 12
Faltando: 0

🎉 Todos os PDFs pos

In [17]:
import json
from pathlib import Path

from langchain_text_splitters import (
    RecursiveCharacterTextSplitter,
    MarkdownHeaderTextSplitter,
)

# ============================================================
# PASTAS
# ============================================================

PASTA_MARKDOWN = Path("markdown")
PASTA_RESULTS = Path("results")

PASTA_RESULTS.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# SPLITTERS
# ============================================================

# 1. Recursive
splitter_recursive = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100,
    separators=[
        "\n\n",
        "\n",
        " ",
        ""
    ],
    length_function=len
)

# 2. Markdown por headings
headers_to_split_on = [
    ("#", "titulo_nivel_1"),
    ("##", "titulo_nivel_2"),
    ("###", "titulo_nivel_3"),
]

splitter_markdown = MarkdownHeaderTextSplitter(
    headers_to_split_on=headers_to_split_on
)


# ============================================================
# FUNÇÃO PARA CHUNKING POR PARÁGRAFOS
# ============================================================

def chunking_paragrafos(texto):
    """
    Divide o texto preservando parágrafos como unidades.
    """
    paragrafos = [
        p.strip()
        for p in texto.split("\n\n")
        if p.strip()
    ]

    return paragrafos


# ============================================================
# FUNÇÃO PARA SALVAR JSON
# ============================================================

def salvar_json(caminho, dados):
    caminho.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        caminho,
        "w",
        encoding="utf-8"
    ) as arquivo:

        json.dump(
            dados,
            arquivo,
            ensure_ascii=False,
            indent=2
        )


# ============================================================
# PROCESSAR TODOS OS MARKDOWNS
# ============================================================

arquivos_md = sorted(
    PASTA_MARKDOWN.glob("*.md")
)

print(
    "Quantidade de documentos:",
    len(arquivos_md)
)

print("=" * 70)


for indice_doc, arquivo_md in enumerate(
    arquivos_md,
    start=1
):

    document_id = f"doc{indice_doc:02d}"
    document_name = arquivo_md.name
    document_slug = arquivo_md.stem

    print(
        f"\n[{indice_doc}/{len(arquivos_md)}] "
        f"Processando: {document_name}"
    )

    texto = arquivo_md.read_text(
        encoding="utf-8"
    )

    pasta_documento = (
        PASTA_RESULTS / document_slug
    )

    # ========================================================
    # ESTRATÉGIA 1 - RECURSIVE
    # ========================================================

    chunks_recursive = (
        splitter_recursive.split_text(texto)
    )

    dados_recursive = []

    for indice_chunk, chunk in enumerate(
        chunks_recursive,
        start=1
    ):

        dados_recursive.append({
            "chunk_id": (
                f"{document_id}_recursive_"
                f"chunk{indice_chunk:03d}"
            ),
            "document_id": document_id,
            "document_name": document_name,
            "strategy": "recursive",
            "chunk_size": 1000,
            "chunk_overlap": 100,
            "text": chunk,
            "metadata": {}
        })

    salvar_json(
        pasta_documento
        / "recursive"
        / "chunks.json",
        dados_recursive
    )

    print(
        f"  ✅ Recursive: "
        f"{len(chunks_recursive)} chunks"
    )


    # ========================================================
    # ESTRATÉGIA 2 - PARÁGRAFOS
    # ========================================================

    chunks_paragrafos = (
        chunking_paragrafos(texto)
    )

    dados_paragrafos = []

    for indice_chunk, chunk in enumerate(
        chunks_paragrafos,
        start=1
    ):

        dados_paragrafos.append({
            "chunk_id": (
                f"{document_id}_paragraph_"
                f"chunk{indice_chunk:03d}"
            ),
            "document_id": document_id,
            "document_name": document_name,
            "strategy": "paragraph",
            "chunk_size": None,
            "chunk_overlap": 0,
            "text": chunk,
            "metadata": {}
        })

    salvar_json(
        pasta_documento
        / "paragraph"
        / "chunks.json",
        dados_paragrafos
    )

    print(
        f"  ✅ Paragraph: "
        f"{len(chunks_paragrafos)} chunks"
    )


    # ========================================================
    # ESTRATÉGIA 3 - MARKDOWN HEADINGS
    # ========================================================

    chunks_markdown = (
        splitter_markdown.split_text(texto)
    )

    dados_markdown = []

    for indice_chunk, chunk in enumerate(
        chunks_markdown,
        start=1
    ):

        dados_markdown.append({
            "chunk_id": (
                f"{document_id}_markdown_"
                f"chunk{indice_chunk:03d}"
            ),
            "document_id": document_id,
            "document_name": document_name,
            "strategy": "markdown",
            "chunk_size": None,
            "chunk_overlap": 0,
            "text": chunk.page_content,
            "metadata": chunk.metadata
        })

    salvar_json(
        pasta_documento
        / "markdown"
        / "chunks.json",
        dados_markdown
    )

    print(
        f"  ✅ Markdown: "
        f"{len(chunks_markdown)} chunks"
    )


print("\n" + "=" * 70)
print("🎉 PROCESSAMENTO FINALIZADO!")

Quantidade de documentos: 12

[1/12] Processando: attention_is_all_you_need.md
  ✅ Recursive: 15 chunks
  ✅ Paragraph: 44 chunks
  ✅ Markdown: 11 chunks

[2/12] Processando: bert_pretraining.md
  ✅ Recursive: 52 chunks
  ✅ Paragraph: 109 chunks
  ✅ Markdown: 18 chunks

[3/12] Processando: bioetica_e_ia.md
  ✅ Recursive: 65 chunks
  ✅ Paragraph: 112 chunks
  ✅ Markdown: 19 chunks

[4/12] Processando: escrita_academica_ia.md
  ✅ Recursive: 50 chunks
  ✅ Paragraph: 89 chunks
  ✅ Markdown: 14 chunks

[5/12] Processando: gpt3_language_models.md
  ✅ Recursive: 412 chunks
  ✅ Paragraph: 593 chunks
  ✅ Markdown: 55 chunks

[6/12] Processando: gpt4_technical_report.md
  ✅ Recursive: 386 chunks
  ✅ Paragraph: 1039 chunks
  ✅ Markdown: 195 chunks

[7/12] Processando: instruct_gpt.md
  ✅ Recursive: 272 chunks
  ✅ Paragraph: 632 chunks
  ✅ Markdown: 116 chunks

[8/12] Processando: llama_foundation_models.md
  ✅ Recursive: 137 chunks
  ✅ Paragraph: 285 chunks
  ✅ Markdown: 54 chunks

[9/12] Processa

In [18]:
def get_embeddings_batch(textos):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=textos,
        encoding_format="float"
    )

    return [
        item.embedding
        for item in resposta.data
    ]

In [19]:
import json
from pathlib import Path

arquivo_teste = Path(
    "results/attention_is_all_you_need/recursive/chunks.json"
)

with open(
    arquivo_teste,
    "r",
    encoding="utf-8"
) as arquivo:
    chunks_teste = json.load(arquivo)

textos_teste = [
    item["text"]
    for item in chunks_teste[:5]
]

embeddings_teste = get_embeddings_batch(
    textos_teste
)

print("Quantidade de textos:", len(textos_teste))
print("Quantidade de embeddings:", len(embeddings_teste))
print(
    "Dimensão de cada embedding:",
    len(embeddings_teste[0])
)

NameError: name 'client' is not defined

In [20]:
import os
from openai import OpenAI

# Coloque sua chave do OpenRouter aqui APENAS para executar localmente
OPENROUTER_API_KEY = "SUA_CHAVE_AQUI"

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

print("✅ Cliente OpenRouter configurado!")

✅ Cliente OpenRouter configurado!


In [21]:
def get_embeddings_batch(textos):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=textos,
        encoding_format="float"
    )

    return [
        item.embedding
        for item in resposta.data
    ]

In [23]:
MODELO_EMBEDDING = "nvidia/llama-nemotron-embed-vl-1b-v2:free"

print("Modelo:", MODELO_EMBEDDING)

Modelo: nvidia/llama-nemotron-embed-vl-1b-v2:free


In [25]:
def get_embeddings_batch(textos):
    resposta = client.embeddings.create(
        model=MODELO_EMBEDDING,
        input=textos,
        encoding_format="float"
    )

    return [
        item.embedding
        for item in resposta.data
    ]

In [26]:
embeddings_teste = get_embeddings_batch(textos_teste)

print("Quantidade de textos:", len(textos_teste))
print("Quantidade de embeddings:", len(embeddings_teste))
print("Dimensão:", len(embeddings_teste[0]))

AuthenticationError: Error code: 401 - {'error': {'message': 'Missing Authentication header', 'code': 401}}

In [27]:
import os
from dotenv import load_dotenv
from openai import OpenAI

# Carrega o arquivo .env da raiz do projeto
load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise ValueError("❌ OPENROUTER_API_KEY não encontrada no arquivo .env")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

print("✅ Chave encontrada!")
print("✅ Cliente OpenRouter configurado!")

✅ Chave encontrada!
✅ Cliente OpenRouter configurado!


In [28]:
embeddings_teste = get_embeddings_batch(textos_teste)

print("Quantidade de textos:", len(textos_teste))
print("Quantidade de embeddings:", len(embeddings_teste))
print("Dimensão:", len(embeddings_teste[0]))

Quantidade de textos: 5
Quantidade de embeddings: 5
Dimensão: 2048


In [31]:
import json
import time
from pathlib import Path

PASTA_RESULTS = Path("results")

TAMANHO_LOTE = 1
PAUSA_ENTRE_LOTES = 0.5

arquivos_chunks = sorted(
    PASTA_RESULTS.glob("*/*/chunks.json")
)

print("Arquivos encontrados:", len(arquivos_chunks))
print("=" * 70)

for numero_arquivo, arquivo_chunks in enumerate(
    arquivos_chunks,
    start=1
):

    arquivo_saida = (
        arquivo_chunks.parent
        / "chunks_embeddings.json"
    )

    print(
        f"\n[{numero_arquivo}/{len(arquivos_chunks)}] "
        f"Processando: {arquivo_chunks}"
    )

    # Se já existir, não processa novamente
    if arquivo_saida.exists():
        print("✅ Já existe. Ignorado.")
        continue

    with open(
        arquivo_chunks,
        "r",
        encoding="utf-8"
    ) as arquivo:
        dados = json.load(arquivo)

    total_chunks = len(dados)

    print("Chunks:", total_chunks)

    resultados = []

    for inicio in range(
        0,
        total_chunks,
        TAMANHO_LOTE
    ):

        fim = min(
            inicio + TAMANHO_LOTE,
            total_chunks
        )

        lote = dados[inicio:fim]

        textos = [
            item["text"]
            for item in lote
        ]

        print(
            f"  ⏳ Embeddings "
            f"{inicio + 1}-{fim}/{total_chunks}...",
            flush=True
        )

        try:
            embeddings = get_embeddings_batch(
                textos
            )

            for item, embedding in zip(
                lote,
                embeddings
            ):
                item_com_embedding = item.copy()

                item_com_embedding[
                    "embedding"
                ] = embedding

                resultados.append(
                    item_com_embedding
                )

            print(
                f"  ✅ Lote {inicio + 1}-{fim} concluído",
                flush=True
            )

            time.sleep(PAUSA_ENTRE_LOTES)

        except Exception as erro:
            print(
                f"  ❌ ERRO no lote "
                f"{inicio + 1}-{fim}: {erro}",
                flush=True
            )

            print(
                "Processamento interrompido "
                "para evitar perda de controle."
            )

            break

    # Só salva se todos os chunks foram processados
    if len(resultados) == total_chunks:

        with open(
            arquivo_saida,
            "w",
            encoding="utf-8"
        ) as arquivo:

            json.dump(
                resultados,
                arquivo,
                ensure_ascii=False,
                indent=2
            )

        print(
            f"✅ Arquivo salvo: "
            f"{arquivo_saida}"
        )

    else:
        print(
            f"⚠️ Arquivo não salvo porque "
            f"foram processados "
            f"{len(resultados)}/{total_chunks} chunks."
        )


print("\n" + "=" * 70)
print("PROCESSAMENTO FINALIZADO")

Arquivos encontrados: 36

[1/36] Processando: results\attention_is_all_you_need\markdown\chunks.json
✅ Já existe. Ignorado.

[2/36] Processando: results\attention_is_all_you_need\paragraph\chunks.json
✅ Já existe. Ignorado.

[3/36] Processando: results\attention_is_all_you_need\recursive\chunks.json
✅ Já existe. Ignorado.

[4/36] Processando: results\bert_pretraining\markdown\chunks.json
✅ Já existe. Ignorado.

[5/36] Processando: results\bert_pretraining\paragraph\chunks.json
✅ Já existe. Ignorado.

[6/36] Processando: results\bert_pretraining\recursive\chunks.json
✅ Já existe. Ignorado.

[7/36] Processando: results\bioetica_e_ia\markdown\chunks.json
✅ Já existe. Ignorado.

[8/36] Processando: results\bioetica_e_ia\paragraph\chunks.json
✅ Já existe. Ignorado.

[9/36] Processando: results\bioetica_e_ia\recursive\chunks.json
✅ Já existe. Ignorado.

[10/36] Processando: results\escrita_academica_ia\markdown\chunks.json
✅ Já existe. Ignorado.

[11/36] Processando: results\escrita_academic

  ✅ Lote 1-1 concluído
  ⏳ Embeddings 2-2/55...
  ✅ Lote 2-2 concluído
  ⏳ Embeddings 3-3/55...
  ✅ Lote 3-3 concluído
  ⏳ Embeddings 4-4/55...
  ✅ Lote 4-4 concluído
  ⏳ Embeddings 5-5/55...
  ✅ Lote 5-5 concluído
  ⏳ Embeddings 6-6/55...
  ✅ Lote 6-6 concluído
  ⏳ Embeddings 7-7/55...
  ✅ Lote 7-7 concluído
  ⏳ Embeddings 8-8/55...
  ✅ Lote 8-8 concluído
  ⏳ Embeddings 9-9/55...
  ✅ Lote 9-9 concluído
  ⏳ Embeddings 10-10/55...
  ✅ Lote 10-10 concluído
  ⏳ Embeddings 11-11/55...
  ✅ Lote 11-11 concluído
  ⏳ Embeddings 12-12/55...
  ✅ Lote 12-12 concluído
  ⏳ Embeddings 13-13/55...
  ✅ Lote 13-13 concluído
  ⏳ Embeddings 14-14/55...
  ✅ Lote 14-14 concluído
  ⏳ Embeddings 15-15/55...
  ✅ Lote 15-15 concluído
  ⏳ Embeddings 16-16/55...
  ✅ Lote 16-16 concluído
  ⏳ Embeddings 17-17/55...
  ✅ Lote 17-17 concluído
  ⏳ Embeddings 18-18/55...
  ✅ Lote 18-18 concluído
  ⏳ Embeddings 19-19/55...
  ✅ Lote 19-19 concluído
  ⏳ Embeddings 20-20/55...
  ✅ Lote 20-20 concluído
  ⏳ Embeddings 21-21/

In [32]:
import json
from pathlib import Path

# Arquivo que apresentou o primeiro problema
arquivo = Path("results/gpt3_language_models/markdown/chunks.json")

with open(arquivo, "r", encoding="utf-8") as f:
    chunks = json.load(f)

# O erro mostrou "53-53".
# Como Python começa em 0, o chunk 53 está no índice 52.
chunk_problematico = chunks[52]

texto = chunk_problematico["text"]

print("Chunk:", 53)
print("Quantidade de caracteres:", len(texto))
print("\nINÍCIO DO CHUNK:")
print("=" * 70)
print(texto[:2000])
print("=" * 70)

Chunk: 53
Quantidade de caracteres: 46447

INÍCIO DO CHUNK:
The following figures illustrate the formatting and phrasing of all the tasks included in the paper. All data comes from the ground truth datasets in this section, and no samples from GPT-3 are included here.  
| Context  →  Article:  Informal  conversation  is  an  important  part  of  any  business  relationship.Before  you  start  a  discussion,however,make  sure  you  understand  which  topics  are  suitable  and  which  are  considered  taboo  in  a  particular  culture.  Latin  Americans  enjoy  sharing  information  about  their  local  history,  art  and  customs.You  may  expect  questions  about  your  family,and  be  sure  to  show  pictures  of  your  children.You  may  feel  free  to  ask  similar  questions  of  your  Latin  American  friends.The  French  think  of  conversation  as  an  art  form,and  they  enjoy  the  value  of  lively  discussions  as  well  as  disagreements.  For  them,arguments  can  be  in

In [34]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
import json
from pathlib import Path

splitter_secundario = RecursiveCharacterTextSplitter(
    chunk_size=6000,
    chunk_overlap=300,
    separators=["\n\n", "\n", " ", ""],
    length_function=len
)

arquivo = Path(
    "results/gpt3_language_models/markdown/chunks.json"
)

with open(arquivo, "r", encoding="utf-8") as f:
    chunks = json.load(f)

chunks_corrigidos = []

for item in chunks:
    texto = item["text"]

    # Agora divide qualquer chunk acima de 6000 caracteres
    if len(texto) > 6000:

        subchunks = splitter_secundario.split_text(texto)

        for i, subchunk in enumerate(subchunks, start=1):

            novo_item = item.copy()

            novo_item["chunk_id"] = (
                f"{item['chunk_id']}_sub{i:02d}"
            )

            novo_item["text"] = subchunk

            novo_item["metadata"] = {
                **item.get("metadata", {}),
                "subdividido": True
            }

            chunks_corrigidos.append(novo_item)

    else:
        chunks_corrigidos.append(item)

print("Chunks originais:", len(chunks))
print("Chunks após correção:", len(chunks_corrigidos))
print(
    "Maior chunk após correção:",
    max(len(x["text"]) for x in chunks_corrigidos)
)

Chunks originais: 55
Chunks após correção: 88
Maior chunk após correção: 5999


In [35]:
arquivo_corrigido = Path(
    "results/gpt3_language_models/markdown/chunks_corrigidos.json"
)

with open(arquivo_corrigido, "w", encoding="utf-8") as f:
    json.dump(
        chunks_corrigidos,
        f,
        ensure_ascii=False,
        indent=2
    )

print("✅ Arquivo corrigido salvo!")

✅ Arquivo corrigido salvo!


In [36]:
import json
from pathlib import Path

arquivo_corrigido = Path(
    "results/gpt3_language_models/markdown/chunks_corrigidos.json"
)

with open(arquivo_corrigido, "r", encoding="utf-8") as f:
    chunks_corrigidos = json.load(f)

print("Total de chunks corrigidos:", len(chunks_corrigidos))
print(
    "Maior tamanho:",
    max(len(item["text"]) for item in chunks_corrigidos)
)

# Teste apenas dos primeiros 5
textos_teste = [
    item["text"]
    for item in chunks_corrigidos[:5]
]

embeddings_teste = get_embeddings_batch(textos_teste)

print("Textos enviados:", len(textos_teste))
print("Embeddings recebidos:", len(embeddings_teste))
print("Dimensão:", len(embeddings_teste[0]))

Total de chunks corrigidos: 88
Maior tamanho: 5999
Textos enviados: 5
Embeddings recebidos: 5
Dimensão: 2048


In [37]:
import json
from pathlib import Path
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter_secundario = RecursiveCharacterTextSplitter(
    chunk_size=6000,
    chunk_overlap=300,
    separators=["\n\n", "\n", " ", ""],
    length_function=len
)

arquivos_problematicos = [
    Path("results/gpt3_language_models/paragraph/chunks.json"),
    Path("results/gpt4_technical_report/markdown/chunks.json"),
]

for arquivo in arquivos_problematicos:

    print("=" * 70)
    print("Processando:", arquivo)

    with open(arquivo, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    chunks_corrigidos = []

    for item in chunks:
        texto = item["text"]

        if len(texto) > 6000:

            subchunks = splitter_secundario.split_text(texto)

            for i, subchunk in enumerate(subchunks, start=1):

                novo_item = item.copy()

                novo_item["chunk_id"] = (
                    f"{item['chunk_id']}_sub{i:02d}"
                )

                novo_item["text"] = subchunk

                novo_item["metadata"] = {
                    **item.get("metadata", {}),
                    "subdividido": True
                }

                chunks_corrigidos.append(novo_item)

        else:
            chunks_corrigidos.append(item)

    arquivo_saida = (
        arquivo.parent
        / "chunks_corrigidos.json"
    )

    with open(
        arquivo_saida,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            chunks_corrigidos,
            f,
            ensure_ascii=False,
            indent=2
        )

    print("Chunks originais:", len(chunks))
    print("Chunks corrigidos:", len(chunks_corrigidos))
    print(
        "Maior chunk:",
        max(len(x["text"]) for x in chunks_corrigidos)
    )
    print("✅ Salvo:", arquivo_saida)

Processando: results\gpt3_language_models\paragraph\chunks.json
Chunks originais: 593
Chunks corrigidos: 599
Maior chunk: 5999
✅ Salvo: results\gpt3_language_models\paragraph\chunks_corrigidos.json
Processando: results\gpt4_technical_report\markdown\chunks.json
Chunks originais: 195
Chunks corrigidos: 211
Maior chunk: 5999
✅ Salvo: results\gpt4_technical_report\markdown\chunks_corrigidos.json


In [38]:
import json
import time
from pathlib import Path

arquivos_corrigidos = [
    Path("results/gpt3_language_models/markdown/chunks_corrigidos.json"),
    Path("results/gpt3_language_models/paragraph/chunks_corrigidos.json"),
    Path("results/gpt4_technical_report/markdown/chunks_corrigidos.json"),
]

# Como já tivemos problema de limite, vamos usar lotes pequenos
TAMANHO_LOTE = 5
PAUSA_ENTRE_LOTES = 0.5

print("=" * 70)
print("GERANDO EMBEDDINGS DOS ARQUIVOS CORRIGIDOS")
print("=" * 70)

for numero, arquivo in enumerate(arquivos_corrigidos, start=1):

    print(f"\n[{numero}/{len(arquivos_corrigidos)}]")
    print("Arquivo:", arquivo)

    with open(arquivo, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    total = len(chunks)
    resultados = []

    print("Total de chunks:", total)

    for inicio in range(0, total, TAMANHO_LOTE):

        fim = min(
            inicio + TAMANHO_LOTE,
            total
        )

        lote = chunks[inicio:fim]

        textos = [
            item["text"]
            for item in lote
        ]

        print(
            f"  ⏳ Embeddings {inicio + 1}-{fim}/{total}...",
            flush=True
        )

        try:

            embeddings = get_embeddings_batch(textos)

            for item, embedding in zip(lote, embeddings):

                novo_item = item.copy()

                novo_item["embedding"] = embedding

                resultados.append(novo_item)

            print(
                f"  ✅ {inicio + 1}-{fim} concluído",
                flush=True
            )

            time.sleep(PAUSA_ENTRE_LOTES)

        except Exception as erro:

            print(
                f"  ❌ ERRO em {inicio + 1}-{fim}: {erro}"
            )

            break

    # Salva somente se TODOS forem processados
    if len(resultados) == total:

        arquivo_saida = (
            arquivo.parent
            / "chunks_embeddings.json"
        )

        with open(
            arquivo_saida,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(
                resultados,
                f,
                ensure_ascii=False,
                indent=2
            )

        print(
            f"  💾 Salvo: {arquivo_saida}"
        )

    else:

        print(
            f"  ⚠️ Incompleto: "
            f"{len(resultados)}/{total}"
        )

print("\n" + "=" * 70)
print("🎉 PROCESSAMENTO DOS CORRIGIDOS FINALIZADO")

GERANDO EMBEDDINGS DOS ARQUIVOS CORRIGIDOS

[1/3]
Arquivo: results\gpt3_language_models\markdown\chunks_corrigidos.json
Total de chunks: 88
  ⏳ Embeddings 1-5/88...
  ✅ 1-5 concluído
  ⏳ Embeddings 6-10/88...
  ✅ 6-10 concluído
  ⏳ Embeddings 11-15/88...
  ✅ 11-15 concluído
  ⏳ Embeddings 16-20/88...
  ✅ 16-20 concluído
  ⏳ Embeddings 21-25/88...
  ✅ 21-25 concluído
  ⏳ Embeddings 26-30/88...
  ✅ 26-30 concluído
  ⏳ Embeddings 31-35/88...
  ✅ 31-35 concluído
  ⏳ Embeddings 36-40/88...
  ✅ 36-40 concluído
  ⏳ Embeddings 41-45/88...
  ✅ 41-45 concluído
  ⏳ Embeddings 46-50/88...
  ✅ 46-50 concluído
  ⏳ Embeddings 51-55/88...
  ✅ 51-55 concluído
  ⏳ Embeddings 56-60/88...
  ✅ 56-60 concluído
  ⏳ Embeddings 61-65/88...
  ✅ 61-65 concluído
  ⏳ Embeddings 66-70/88...
  ✅ 66-70 concluído
  ⏳ Embeddings 71-75/88...
  ✅ 71-75 concluído
  ⏳ Embeddings 76-80/88...
  ✅ 76-80 concluído
  ⏳ Embeddings 81-85/88...
  ✅ 81-85 concluído
  ⏳ Embeddings 86-88/88...
  ✅ 86-88 concluído
  💾 Salvo: results\g

In [39]:
from pathlib import Path
import json

PASTA_RESULTS = Path("results")

arquivos_embeddings = sorted(
    PASTA_RESULTS.glob("*/*/chunks_embeddings.json")
)

print("=" * 70)
print("VERIFICAÇÃO FINAL DOS EMBEDDINGS")
print("=" * 70)

print("Arquivos encontrados:", len(arquivos_embeddings))

problemas = []

for arquivo in arquivos_embeddings:

    with open(arquivo, "r", encoding="utf-8") as f:
        dados = json.load(f)

    if len(dados) == 0:
        problemas.append(f"{arquivo} - arquivo vazio")
        continue

    dimensoes = {
        len(item["embedding"])
        for item in dados
        if "embedding" in item
    }

    if dimensoes != {2048}:
        problemas.append(
            f"{arquivo} - dimensões encontradas: {dimensoes}"
        )

print()

if len(problemas) == 0:
    print("✅ Todos os arquivos possuem embeddings válidos.")
else:
    print("⚠️ Problemas encontrados:")
    for problema in problemas:
        print("-", problema)

print("\nResumo:")
print("Esperados: 36")
print("Encontrados:", len(arquivos_embeddings))
print("Problemas:", len(problemas))

VERIFICAÇÃO FINAL DOS EMBEDDINGS
Arquivos encontrados: 36

✅ Todos os arquivos possuem embeddings válidos.

Resumo:
Esperados: 36
Encontrados: 36
Problemas: 0


In [40]:
import json
from pathlib import Path

arquivo_summary = Path("summary.json")

if not arquivo_summary.exists():
    # caso esteja dentro de results/
    arquivo_summary = Path("results/summary.json")

if arquivo_summary.exists():
    print("Arquivo encontrado:", arquivo_summary)
    print("=" * 70)

    with open(arquivo_summary, "r", encoding="utf-8") as f:
        summary = json.load(f)

    print(json.dumps(summary, ensure_ascii=False, indent=2)[:5000])

else:
    print("❌ summary.json não encontrado.")

Arquivo encontrado: results\summary.json
{
  "document": "bioetica_e_ia.md",
  "embedding_model": "nvidia/llama-nemotron-embed-vl-1b-v2:free",
  "embedding_dimension": 2048,
  "experiments": [
    {
      "test_id": 1,
      "strategy": "fixed",
      "chunk_size": 200,
      "chunk_overlap": 0,
      "num_chunks": 222,
      "avg_chunk_size": 199.42,
      "min_chunk_size": 146,
      "max_chunk_size": 200,
      "embedding_dimension": 2048
    },
    {
      "test_id": 2,
      "strategy": "fixed",
      "chunk_size": 500,
      "chunk_overlap": 0,
      "num_chunks": 89,
      "avg_chunk_size": 497.92,
      "min_chunk_size": 347,
      "max_chunk_size": 500,
      "embedding_dimension": 2048
    },
    {
      "test_id": 3,
      "strategy": "fixed",
      "chunk_size": 1000,
      "chunk_overlap": 0,
      "num_chunks": 45,
      "avg_chunk_size": 985.13,
      "min_chunk_size": 347,
      "max_chunk_size": 1000,
      "embedding_dimension": 2048
    },
    {
      "test_id": 4,
 

In [41]:
import json
from pathlib import Path

PASTA_RESULTS = Path("results")

# ============================================================
# CONFIGURAÇÕES
# ============================================================

MODELO = "nvidia/llama-nemotron-embed-vl-1b-v2:free"
DIMENSAO = 2048

estrategias = [
    "recursive",
    "paragraph",
    "markdown"
]

# ============================================================
# IDENTIFICAR DOCUMENTOS
# ============================================================

documentos = sorted([
    pasta
    for pasta in PASTA_RESULTS.iterdir()
    if pasta.is_dir()
])

summary_corpus = {
    "embedding_model": MODELO,
    "embedding_dimension": DIMENSAO,
    "total_documents": len(documentos),
    "strategies": estrategias,
    "documents": []
}

# ============================================================
# PROCESSAR CADA DOCUMENTO
# ============================================================

for pasta_documento in documentos:

    documento = {
        "document": pasta_documento.name + ".md",
        "strategies": {}
    }

    for estrategia in estrategias:

        pasta_estrategia = (
            pasta_documento / estrategia
        )

        arquivo_embeddings = (
            pasta_estrategia
            / "chunks_embeddings.json"
        )

        # Caso não exista, pula
        if not arquivo_embeddings.exists():
            continue

        with open(
            arquivo_embeddings,
            "r",
            encoding="utf-8"
        ) as f:
            chunks = json.load(f)

        tamanhos = [
            len(item["text"])
            for item in chunks
        ]

        # Verificar se houve subdivisão de chunks grandes
        chunks_subdivididos = sum(
            1
            for item in chunks
            if item.get("metadata", {}).get(
                "subdividido",
                False
            )
        )

        dimensoes = [
            len(item["embedding"])
            for item in chunks
            if "embedding" in item
        ]

        documento["strategies"][estrategia] = {
            "num_chunks": len(chunks),
            "avg_chunk_size": (
                round(sum(tamanhos) / len(tamanhos), 2)
                if tamanhos else 0
            ),
            "min_chunk_size": (
                min(tamanhos)
                if tamanhos else 0
            ),
            "max_chunk_size": (
                max(tamanhos)
                if tamanhos else 0
            ),
            "embedding_dimension": (
                dimensoes[0]
                if dimensoes else None
            ),
            "subdivided_chunks": chunks_subdivididos
        }

    summary_corpus["documents"].append(
        documento
    )

# ============================================================
# SALVAR
# ============================================================

arquivo_saida = (
    PASTA_RESULTS
    / "summary_corpus.json"
)

with open(
    arquivo_saida,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        summary_corpus,
        f,
        ensure_ascii=False,
        indent=2
    )

# ============================================================
# RESULTADO
# ============================================================

print("=" * 70)
print("SUMMARY DO CORPUS")
print("=" * 70)

print("Documentos:", len(documentos))
print("Estratégias:", len(estrategias))
print(
    "Combinações esperadas:",
    len(documentos) * len(estrategias)
)

print("\n✅ Arquivo criado:")
print(arquivo_saida)

SUMMARY DO CORPUS
Documentos: 12
Estratégias: 3
Combinações esperadas: 36

✅ Arquivo criado:
results\summary_corpus.json


In [42]:
with open(
    "results/summary_corpus.json",
    "r",
    encoding="utf-8"
) as f:
    resumo = json.load(f)

print(json.dumps(
    resumo,
    ensure_ascii=False,
    indent=2
)[:5000])

{
  "embedding_model": "nvidia/llama-nemotron-embed-vl-1b-v2:free",
  "embedding_dimension": 2048,
  "total_documents": 12,
  "strategies": [
    "recursive",
    "paragraph",
    "markdown"
  ],
  "documents": [
    {
      "document": "attention_is_all_you_need.md",
      "strategies": {
        "recursive": {
          "num_chunks": 15,
          "avg_chunk_size": 784.93,
          "min_chunk_size": 242,
          "max_chunk_size": 997,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "paragraph": {
          "num_chunks": 44,
          "avg_chunk_size": 258.45,
          "min_chunk_size": 11,
          "max_chunk_size": 1138,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        },
        "markdown": {
          "num_chunks": 11,
          "avg_chunk_size": 1018.27,
          "min_chunk_size": 173,
          "max_chunk_size": 2134,
          "embedding_dimension": 2048,
          "subdivided_chunks": 0
        }
 

## Busca semântica nos chunks

Nesta etapa, utilizamos os embeddings gerados para realizar buscas semânticas nos documentos e comparar o comportamento das diferentes estratégias de chunking.

In [43]:
import numpy as np

def similaridade_cosseno(a, b):
    a = np.array(a)
    b = np.array(b)

    return np.dot(a, b) / (
        np.linalg.norm(a) * np.linalg.norm(b)
    )

print("✅ Função de similaridade criada!")

✅ Função de similaridade criada!


In [44]:
# Pergunta que será usada na busca semântica
pergunta = "Como os modelos de linguagem utilizam mecanismos de atenção?"

# Gerar embedding da pergunta usando o mesmo modelo
embedding_pergunta = get_embeddings_batch([pergunta])[0]

print("Pergunta:", pergunta)
print("Dimensão do embedding:", len(embedding_pergunta))

Pergunta: Como os modelos de linguagem utilizam mecanismos de atenção?
Dimensão do embedding: 2048


In [45]:
import json
from pathlib import Path

resultados_busca = []

arquivos_recursive = sorted(
    Path("results").glob("*/recursive/chunks_embeddings.json")
)

for arquivo in arquivos_recursive:

    with open(arquivo, "r", encoding="utf-8") as f:
        chunks = json.load(f)

    for item in chunks:
        score = similaridade_cosseno(
            embedding_pergunta,
            item["embedding"]
        )

        resultados_busca.append({
            "documento": item["document_name"],
            "chunk_id": item["chunk_id"],
            "score": float(score),
            "texto": item["text"]
        })

# Ordenar do mais semelhante para o menos semelhante
resultados_busca = sorted(
    resultados_busca,
    key=lambda x: x["score"],
    reverse=True
)

top_5 = resultados_busca[:5]

for i, resultado in enumerate(top_5, start=1):
    print("=" * 80)
    print(f"TOP {i}")
    print("Documento:", resultado["documento"])
    print("Chunk:", resultado["chunk_id"])
    print("Score:", round(resultado["score"], 4))
    print("\nTrecho:")
    print(resultado["texto"][:1500])
    print()

TOP 1
Documento: llama_foundation_models.md
Chunk: doc08_recursive_chunk056
Score: 0.3436

Trecho:
## 7 Related work

Language models are probability distributions over sequences of words, tokens or characters (Shannon, 1948, 1951). This task, often framed as next token prediction, has long been considered a core problem in natural language processing (Bahl et al., 1983; Brown et al., 1990). Because Turing (1950) proposed to measure machine intelligence by using language through the 'imitation game', language modeling has been proposed as a benchmark to measure progress toward artificial intelligence (Mahoney, 1999).

Architecture. Traditionally, language models were based on n -gram count statistics (Bahl et al., 1983), and various smoothing techniques were proposed to improve the estimation of rare events (Katz, 1987; Kneser and Ney, 1995). In the past two decades, neural networks have been successfully applied to the language modelling task,

TOP 2
Documento: gpt3_language_models.md

In [46]:
import json
from pathlib import Path

def buscar_top_k(estrategia, embedding_query, top_k=5):
    resultados = []

    arquivos = sorted(
        Path("results").glob(
            f"*/{estrategia}/chunks_embeddings.json"
        )
    )

    for arquivo in arquivos:
        with open(arquivo, "r", encoding="utf-8") as f:
            chunks = json.load(f)

        for item in chunks:
            score = similaridade_cosseno(
                embedding_query,
                item["embedding"]
            )

            resultados.append({
                "estrategia": estrategia,
                "documento": item["document_name"],
                "chunk_id": item["chunk_id"],
                "score": float(score),
                "texto": item["text"]
            })

    resultados = sorted(
        resultados,
        key=lambda x: x["score"],
        reverse=True
    )

    return resultados[:top_k]

In [48]:
estrategias_busca = [
    "recursive",
    "paragraph",
    "markdown"
]

resultados_comparacao = {}

for estrategia in estrategias_busca:
    resultados_comparacao[estrategia] = buscar_top_k(
        estrategia,
        embedding_pergunta,
        top_k=5
    )

print("✅ Comparação realizada!")

✅ Comparação realizada!


In [49]:
for estrategia, resultados in resultados_comparacao.items():

    print("\n" + "#" * 90)
    print("ESTRATÉGIA:", estrategia.upper())
    print("#" * 90)

    for i, resultado in enumerate(resultados, start=1):

        print("\n" + "=" * 80)
        print(f"TOP {i}")
        print("Documento:", resultado["documento"])
        print("Score:", round(resultado["score"], 4))
        print("Chunk:", resultado["chunk_id"])

        print("\nTrecho:")
        print(resultado["texto"][:1000])


##########################################################################################
ESTRATÉGIA: RECURSIVE
##########################################################################################

TOP 1
Documento: llama_foundation_models.md
Score: 0.3436
Chunk: doc08_recursive_chunk056

Trecho:
## 7 Related work

Language models are probability distributions over sequences of words, tokens or characters (Shannon, 1948, 1951). This task, often framed as next token prediction, has long been considered a core problem in natural language processing (Bahl et al., 1983; Brown et al., 1990). Because Turing (1950) proposed to measure machine intelligence by using language through the 'imitation game', language modeling has been proposed as a benchmark to measure progress toward artificial intelligence (Mahoney, 1999).

Architecture. Traditionally, language models were based on n -gram count statistics (Bahl et al., 1983), and various smoothing techniques were proposed to improve the e

In [50]:
perguntas_teste = [
    "Como os modelos de linguagem utilizam mecanismos de atenção?",
    "Como o aprendizado por reforço com feedback humano é utilizado para alinhar modelos de linguagem?",
    "Como a recuperação de documentos externos pode melhorar as respostas de modelos de linguagem?"
]

In [51]:
embeddings_perguntas = get_embeddings_batch(perguntas_teste)

print("Quantidade de perguntas:", len(perguntas_teste))
print("Quantidade de embeddings:", len(embeddings_perguntas))
print("Dimensão de cada embedding:", len(embeddings_perguntas[0]))

Quantidade de perguntas: 3
Quantidade de embeddings: 3
Dimensão de cada embedding: 2048


In [52]:
resultados_multiplas_perguntas = {}

for pergunta, embedding_query in zip(
    perguntas_teste,
    embeddings_perguntas
):
    resultados_multiplas_perguntas[pergunta] = {}

    for estrategia in [
        "recursive",
        "paragraph",
        "markdown"
    ]:
        resultados_multiplas_perguntas[pergunta][estrategia] = buscar_top_k(
            estrategia,
            embedding_query,
            top_k=3
        )

print("✅ Busca das 3 perguntas concluída!")

✅ Busca das 3 perguntas concluída!


In [53]:
for pergunta, resultados_estrategias in resultados_multiplas_perguntas.items():

    print("\n" + "#" * 100)
    print("PERGUNTA:")
    print(pergunta)
    print("#" * 100)

    for estrategia, resultados in resultados_estrategias.items():

        print(f"\nESTRATÉGIA: {estrategia.upper()}")

        for i, resultado in enumerate(resultados, start=1):
            print(
                f"TOP {i} | "
                f"{resultado['documento']} | "
                f"Score: {resultado['score']:.4f}"
            )

        print("-" * 80)


####################################################################################################
PERGUNTA:
Como os modelos de linguagem utilizam mecanismos de atenção?
####################################################################################################

ESTRATÉGIA: RECURSIVE
TOP 1 | llama_foundation_models.md | Score: 0.3416
TOP 2 | gpt3_language_models.md | Score: 0.3411
TOP 3 | instruct_gpt.md | Score: 0.3276
--------------------------------------------------------------------------------

ESTRATÉGIA: PARAGRAPH
TOP 1 | escrita_academica_ia.md | Score: 0.4275
TOP 2 | gpt3_language_models.md | Score: 0.4126
TOP 3 | attention_is_all_you_need.md | Score: 0.3739
--------------------------------------------------------------------------------

ESTRATÉGIA: MARKDOWN
TOP 1 | llama_foundation_models.md | Score: 0.3052
TOP 2 | llama_foundation_models.md | Score: 0.3039
TOP 3 | attention_is_all_you_need.md | Score: 0.3025
-----------------------------------------------------

In [54]:
import pandas as pd

linhas = []

for pergunta, estrategias in resultados_multiplas_perguntas.items():

    for estrategia, resultados in estrategias.items():

        top1 = resultados[0]

        linhas.append({
            "Pergunta": pergunta,
            "Estratégia": estrategia,
            "TOP 1": top1["documento"],
            "Score TOP 1": round(top1["score"], 4),
            "TOP 2": resultados[1]["documento"],
            "Score TOP 2": round(resultados[1]["score"], 4),
            "TOP 3": resultados[2]["documento"],
            "Score TOP 3": round(resultados[2]["score"], 4)
        })

df_comparacao = pd.DataFrame(linhas)

df_comparacao

,Pergunta,Estratégia,TOP 1,Score TOP 1,TOP 2,Score TOP 2,TOP 3,Score TOP 3
0,Como os modelos de linguagem utilizam mecanism...,recursive,llama_foundation_models.md,0.3416,gpt3_language_models.md,0.3411,instruct_gpt.md,0.3276
1,Como os modelos de linguagem utilizam mecanism...,paragraph,escrita_academica_ia.md,0.4275,gpt3_language_models.md,0.4126,attention_is_all_you_need.md,0.3739
2,Como os modelos de linguagem utilizam mecanism...,markdown,llama_foundation_models.md,0.3052,llama_foundation_models.md,0.3039,attention_is_all_you_need.md,0.3025
3,Como o aprendizado por reforço com feedback hu...,recursive,gpt4_technical_report.md,0.5314,instruct_gpt.md,0.5179,instruct_gpt.md,0.4435
4,Como o aprendizado por reforço com feedback hu...,paragraph,instruct_gpt.md,0.5282,gpt4_technical_report.md,0.5257,instruct_gpt.md,0.5131
5,Como o aprendizado por reforço com feedback hu...,markdown,instruct_gpt.md,0.4312,instruct_gpt.md,0.4103,gpt4_technical_report.md,0.3819
6,Como a recuperação de documentos externos pode...,recursive,retrieval_augmented_generation.md,0.3621,retrieval_augmented_generation.md,0.3532,gpt3_language_models.md,0.3251
7,Como a recuperação de documentos externos pode...,paragraph,retrieval_augmented_generation.md,0.3620,retrieval_augmented_generation.md,0.3592,escrita_academica_ia.md,0.3465
8,Como a recuperação de documentos externos pode...,markdown,retrieval_augmented_generation.md,0.3524,retrieval_augmented_generation.md,0.3308,retrieval_augmented_generation.md,0.3305


## Análise comparativa das estratégias de chunking

Foram realizadas três consultas semânticas relacionadas a diferentes temas presentes no corpus: mecanismos de atenção, alinhamento de modelos por aprendizado por reforço com feedback humano (RLHF) e recuperação aumentada por geração (RAG). Para cada consulta, foram comparadas as estratégias Recursive, Paragraph e Markdown, considerando os três chunks com maior similaridade semântica.

Os resultados demonstram que nenhuma estratégia apresentou desempenho superior em todos os cenários. Na consulta relacionada aos mecanismos de atenção, o documento *Attention Is All You Need* não ocupou a primeira posição em nenhuma estratégia, embora tenha sido recuperado entre os três primeiros resultados pelas estratégias Paragraph e Markdown.

Na consulta sobre RLHF e alinhamento de modelos, a estratégia Paragraph apresentou um resultado particularmente coerente, recuperando *InstructGPT* na primeira posição. As demais estratégias também recuperaram documentos diretamente relacionados ao tema, especialmente *InstructGPT* e o relatório técnico do GPT-4.

Para a consulta relacionada à recuperação de documentos externos, as três estratégias apresentaram comportamento consistente, recuperando *Retrieval-Augmented Generation* entre os resultados mais relevantes. Nesse caso, Recursive e Paragraph apresentaram scores de similaridade muito próximos na primeira posição.

Esses resultados indicam que o valor numérico da similaridade não deve ser interpretado isoladamente como medida absoluta da qualidade da recuperação. A relevância semântica do conteúdo recuperado também precisa ser considerada. Além disso, diferentes formas de segmentação modificam o contexto representado pelos embeddings e, consequentemente, a posição dos documentos nos resultados da busca.

De maneira geral, a estratégia Paragraph apresentou bons resultados em consultas específicas, enquanto Recursive demonstrou maior regularidade no tamanho dos chunks e resultados consistentes de recuperação. Markdown preservou melhor a estrutura documental, porém produziu segmentos maiores e exigiu subdivisão adicional em alguns documentos para respeitar os limites do modelo de embeddings.